
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'production-stage'
    ports:
    - '8080:80'
    volumes:
    - '.:/app'
    # command: /bin/sh -c "yarn && quasar build"

# version: "3.7"

# services:
#   front:
#     container_name: front
#     build:
#       context: .
#       dockerfile: Dockerfile-prod
#     ports:
#       - '8080:8080'
