
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'production-stage'
    ports:
    - '80:80'
    - 443:443
    volumes:
    - '.:/app'

    # command: /bin/sh -c "yarn && quasar build"
  # nginx:
  #   image: nginx:1.13
  #   container_name: nginx
  #   restart: always
  #   ports:
  #       - "80:80"
  #       - "443:443"
  #   volumes:
  #       - ./nginx/conf.d:/etc/nginx/conf.d

# version: "3.7"

# services:
#   front:
#     container_name: front
#     build:
#       context: .
#       dockerfile: Dockerfile-prod
#     ports:
#       - '8080:8080'
